# Generated by Django 4.0.5 on 2022-06-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=70)),
                ('marca', models.CharField(default='', max_length=70)),
                ('cantidad', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('precioIva', models.FloatField(default=0)),
            ],
        ),
    ]
