# Generated by Django 4.0.5 on 2022-06-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('brand', models.CharField(default='', max_length=70)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0)),
                ('iva', models.FloatField(default=0)),
                ('priceIva', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
